language: node_js
node_js:
- node
- lts/*
- '6'
- '4'
install: npm install
before_install:
- if [[ `npm -v` = 2* ]]; then npm i -g npm@3; fi
env:
  global:
    secure: TEg8AET7c5uihr3DLCglmvzxVyl55xiRsmBo7LGf/ryGa3ASaaPY7ZOOr8745xIVZ/C0OAdB+Ot+StfARK/lxrFf/9coax25+afHGASH4Tz2yd6Hfmqrk9mS4CL9IVfUbTRVWXsH7uUjge2SCADJnP06WSCFe1wN+lB+HWzIUwpw0byFbKZvw5kmbRWQe40Osg7macad3TCMajkxWJ4mn6XYG6Qlo9wimyRnn+vEw+jSj0GZNM8YdYiCWJGVVOLTry1hb2b2N4oi8JGVHgmJg+YZAkaX8smumlz98qyo0OaeCkNc4gfaSWnGYF6U+r9HX3MFmsuLUQzQo+vY9a2ZorQpsHHkpYVcsn4EG+mmt4EuaTn2lOnxWrDnKAzFMsiw0qOeyo/oH5mgi2KyRyxMPqG4RCfAeJ0003OZ8ChzhUq7SvMzi4U0RfzNNFMnDVp6NuhInTAAYwIUSf20T14b9p54iXm+ZgaJ/m00geqZla2seAJcXuxjRlkrH4/unOXNxjl3vzRlh7buKgIlBTbmVq9s2IN28gLaSuPRZNphlyMEkjjDg/9f4OIm3tdIwf4fam49gReOKDcqW4LGQgnLOHaWCaZbogpNLw+VPPQTRkqXBIMBdrVrWBKh+SGyyibj19X9d4C/HnZPNq3z2jt0PRyqWrc5nJBBGG+CLV2E4dk=
